const express = require("express");
const router = express();
const postController = require("../controllers/post.controller");
const authMiddleware = require("../../middleware/authMiddleware");
router.post("/post", postController.createPost);
router.post("/like_post", authMiddleware, postController.likePost);
router.get("/posts", postController.getPosts);
router.get("/post/:id", postController.getOnePost);
router.get("/posts/user", postController.getPostsByUser);
router.delete("/post/:id", postController.deletePost);
router.get("/test", postController.test);
module.exports = router;
